# Generated by Django 2.2 on 2021-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_end',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('end_url', models.CharField(blank=True, max_length=200, null=True)),
                ('check_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
