# Generated by Django 2.2 on 2021-11-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0004_auto_20211130_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_cases',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
