# Generated by Django 2.2 on 2021-11-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0004_db_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_cases',
            name='retry_count',
            field=models.IntegerField(default=2),
        ),
    ]
