# Generated by Django 2.2 on 2021-11-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0005_db_cases_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_end',
            name='max_bf',
        ),
        migrations.RemoveField(
            model_name='db_end',
            name='user',
        ),
    ]
