# Generated by Django 2.2 on 2021-11-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0006_auto_20211130_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_cases',
            name='status',
        ),
    ]
