# Generated by Django 2.2 on 2021-11-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0007_remove_db_cases_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_end',
            name='max_threads',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='db_end',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
