# Generated by Django 2.2 on 2021-12-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0009_merge_20211203_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_end',
            name='check_time',
            field=models.IntegerField(default=60),
        ),
    ]
