# Generated by Django 2.2 on 2021-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0010_auto_20211203_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_end',
            name='monitor_host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
