# Generated by Django 2.2 on 2021-12-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiApp', '0013_db_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_locator',
            name='page_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
